### ISSUE TITLE
400 Bad Request on interactive messages

### ISSUE THREAD

**Issue by marluanespiritusanto** [WhatsApp/WhatsApp-Nodejs-SDK#12]
# Prerequisites
Please ensure the following are done before submitting an issue:

- [x] I am running the latest version compatible with my Cloud API version.
- [x] I searched the official documentation but found no answer.
- [x] I made sure that this issue is not a duplicate of an existing issue.

# Expected behavior
Using the `interactive` method of the `messages` object should send an interactive message (button or list).

# Current behavior
The method returns a 400 Bad Request because an unexpected property is sent: `interactive`.

# Failure information (for bug reporting)
If this is a bug, please complete the sections below. Otherwise, delete and enter your feature request here.

## Steps to Reproduce
Detailed steps to reproduce the issue. Be as detailed as possible without compromising any sensitive data.

```ts
async sendButtons(message: string, recipientNumber: number) {
    try {
      const response = await this.whatsapp.messages.interactive(
        {
          interactive: {
            type: InteractiveTypesEnum.Button,
            body: {
              text: message,
            },
            action: {
              buttons: [
                {
                  type: "reply",
                  reply: {
                    id: "0001",
                    title: "Example 1",
                  },
                },
                {
                  type: "reply",
                  reply: {
                    id: "0002",
                    title: "Example 2",
                  },
                },
              ],
            },
          },
        },
        recipientNumber
      );

      response.responseBodyToJSON().then((data) => {
        console.log(data); // 400 bad request
      });
    } catch (ex) {
      console.log(ex);
    }
  }
```

## Context
Please provide any other relevant information about your application or configuration.

* Are you a BSP (yes/no): yes
* Operating system or other system info (e.g. cloud stack): MacOS
* Node.js version: v18.12.1
* SDK version: 0.0.4-Alpha
* Cloud API version: v16.0

The request is supposed to be like this:
```json
{
    "messaging_product": "whatsapp",
    "recipient_type": "individual",
    "to": "10000000000",
    "type": "interactive",
    "interactive": {
        ...
    }
}
```

this is what is being sent instead:
```json
{
    "messaging_product": "whatsapp",
    "recipient_type": "individual",
    "to": "10000000000",
    "type": "interactive",
    "interactive": {
        "interactive": {
               ...
        }
    }
}
```

The problem is here in this [line](https://github.com/WhatsApp/WhatsApp-Nodejs-SDK/blob/main/src/api/messages.ts#L50). 

## Failure Logs
Please paste any relevant logs here. REMEMBER TO REMOVE ANY/ALL sensitive data (e.g. phone numbers, names, security keys, etc.)!!!

```json
{
    "code": 100
    "fbtrace_id": "AobQ4HleWGGHWMbkW47A88E"
    "message": "(#100) Unexpected key 'interactive' on param 'interactive'."
    "type": "OAuthException"
}
```

**Comment by rashedtalukder** [comment]
@marluanespiritusanto, can you reference what docs you say you're looking at? The WhatsApp SDK docs state that you need to send the InteractiveObject as the argument to body for sending a button:
https://whatsapp.github.io/WhatsApp-Nodejs-SDK/api-reference/messages/interactive

The object you pass in should be [InteractiveObject](https://whatsapp.github.io/WhatsApp-Nodejs-SDK/api-reference/types/InteractiveObject), which should not have the parent "interactive" key.

**Comment by marluanespiritusanto** [comment]
@rashedtalukder I agree with you, the documentation does not indicate that an `interactive` property is required, but if you check this [line](https://github.com/WhatsApp/WhatsApp-Nodejs-SDK/blob/main/src/types/messages.ts#L251), you will see that it is.

```ts
export type InteractiveObject = {
	[MessageTypesEnum.Interactive]:
		| ButtonInteractiveObject
		| ListInteractiveObject
		| ProductInteractiveObject
		| ProductListInteractiveObject;
};
```

**Comment by rashedtalukder** [comment]
Appreciate the follow up and you are right. I pushed a new branch that should remedy that issue. Let me know if it resolves your issue and I'll see about adding it to the main line: https://github.com/WhatsApp/WhatsApp-Nodejs-SDK/tree/hotfix/InteractiveObject
