### ISSUE TITLE
Incompatible types for `WebhookCallback` in docs

### ISSUE THREAD

**Issue by hamza-shezad** [WhatsApp/WhatsApp-Nodejs-SDK#25]
# Expected behavior
The type mentioned for the webhook callback should be the same as in the source file:

https://github.com/WhatsApp/WhatsApp-Nodejs-SDK/blob/1613e41959368f4033cf54a10b52c15962cc0759/src/types/webhooks.ts#L241-L247

# Current behavior
Currently, showing

https://github.com/WhatsApp/WhatsApp-Nodejs-SDK/blob/1613e41959368f4033cf54a10b52c15962cc0759/website/docs/receiving_messages.md?plain=1#L50

**Comment by rashedtalukder** [comment]
Thank you for catching that @hamza-shezad. Code is correct, docs is not since error should be optional. Will fix that soon in an upcoming branch.
