### ISSUE TITLE
feature request: bulk messaging

### ISSUE THREAD

**Issue by clivi-kj** [WhatsApp/WhatsApp-Nodejs-SDK#27]
# Expected behavior
Bulk message in one call

# Current behavior
Currently, don't see this as an option.

# Failure information (for bug reporting)
Feature request: ability to send same message to multiple recipients 

## Context
Please provide any other relevant information about your application or configuration.

* Are you a BSP (yes/no): no
* Operating system or other system info (e.g. cloud stack):
* Node.js version: 18
* SDK version: 0.0.4
* Cloud API version: 16

**Comment by dmitryvinn-fb** [comment]
Closing - please read more in the [following issue](https://github.com/WhatsApp/WhatsApp-Nodejs-SDK/issues/31).
