### ISSUE TITLE
MaxListenersExceeded Warning

### ISSUE THREAD

**Issue by zolero** [WhatsApp/WhatsApp-Nodejs-SDK#3]
# Expected behavior
It should just handle the incoming http request and not add the socket to the sockets set. Since it doesn't do anything with it after it's received.

# Current behavior
Currently I'm encountering a max event listener error. I'm not really sure why it's adding a socket connection to the set each incoming http connection. 

https://github.com/WhatsApp/WhatsApp-Nodejs-SDK/blob/7daa8cdf08462a30622ad6daed83112f37cf6b09/src/httpsServer.ts#L25-L32

## Context
* Node.js version: v18.12.0
* SDK version: ^0.0.3-Alpha

## Failure Logs
```md
(node:10192) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [Server]. Use emitter.setMaxListeners() to increase limit (Use `node --trace-warnings ...` to show where the warning was created)
```

![image](https://user-images.githubusercontent.com/6997299/229787293-e35cdc33-f7b0-4f2d-8929-46daf6f458de.png)

**Comment by rashedtalukder** [comment]
I'm thinking of changing the entire webhooks APIs in the SDK to only use event emitters and the SDK handles the response back to the Cloud API. Right now, I leave it up to the developer so they can maximize what they do with the response object and handle the logic based on their own needs.

@zolero, what are your thoughts?
